Update form.tsx
SevanBadal/legibill pull request #4
Opened 2023-12-26 06:43 UTC by saro9588

2023-12-27 00:14 UTC, SevanBadal requested changes
Please add a detailed description to this PR. 'll review afterwards! Thanks @saro9588

2023-12-27 00:38 UTC, SevanBadal commented on app/api/auth/register/route.ts
> +            { error: "User with provided email already exists." },
Responding with a message that indicates a user is already created with a given email exposes us to [user enumeration attacks](https://wiki.owasp.org/index.php/Testing_for_User_Enumeration_and_Guessable_User_Account_(OWASP-AT-002)).

2024-01-21 04:03 UTC, saro9588 commented on app/api/auth/register/route.ts
> +        const data: QueryResult = await sql`
done

2024-01-28 20:41 UTC, SevanBadal approved these changes
Looks good! Thanks, @saro9588

2024-01-28 20:42 UTC, merged